project_id = "kzcowengsnnuglyrjuto"

[functions.voice-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.elevenlabs-signed-url]
verify_jwt = false

[functions.send-activity-reminders]
verify_jwt = false

[functions.update-elevenlabs-agent]
verify_jwt = false

[functions.translate-activity]
verify_jwt = true
